services:
  - type: web
    name: klass-backend
    runtime: docker
    plan: free
    region: singapore
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeployTrigger: commit
    healthCheckPath: /up
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: LOG_STACK
        value: single
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_STORAGE_KEY
        sync: false
      - key: SUPABASE_STORAGE_SECRET
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        sync: false
      - key: SUPABASE_STORAGE_ENDPOINT
        sync: false
      - key: SUPABASE_STORAGE_REGION
        value: ap-southeast-1
      - key: MAIL_MAILER
        value: log
      - key: LARAVEL_CACHE_AT_STARTUP
        value: "true"
      - key: RUN_MIGRATIONS
        value: "false"