import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';

/// Full-screen preview screen that loads a self-contained HTML artifact
/// (Jinja2-generated preview) inside an ``InAppWebView``.
///
/// The preview is a self-contained HTML file with inline CSS served via
/// signed URL from the media generator service. No CORS issues, no external
/// network requests — the browser engine renders it in-place.
///
/// After the Marp-to-Jinja2 migration, the HTML is generated by
/// :class:`HtmlTemplateEngine` using a master template with design tokens
/// that match the PPTX master for visual parity.
class MediaPreviewScreen extends StatefulWidget {
  const MediaPreviewScreen({
    super.key,
    required this.previewUrl,
    this.title,
  });

  /// Signed URL for the self-contained HTML preview.
  final String previewUrl;

  /// Optional display title (shown in the app bar).
  final String? title;

  @override
  State<MediaPreviewScreen> createState() => _MediaPreviewScreenState();
}

class _MediaPreviewScreenState extends State<MediaPreviewScreen> {
  double _progress = 0.0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.title ?? 'Preview',
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: const TextStyle(
            fontFamily: 'Mona_Sans',
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: Colors.white,
          ),
        ),
        backgroundColor: const Color(0xFF0E4C5C),
        iconTheme: const IconThemeData(color: Colors.white),
        bottom: _progress < 1.0
            ? PreferredSize(
                preferredSize: const Size.fromHeight(4),
                child: LinearProgressIndicator(
                  value: _progress,
                  color: Colors.white,
                  backgroundColor: Colors.white24,
                ),
              )
            : null,
      ),
      body: InAppWebView(
        initialUrlRequest: URLRequest(
          url: WebUri(widget.previewUrl),
        ),
        initialSettings: InAppWebViewSettings(
          javaScriptEnabled: true,
          verticalScrollBarEnabled: true,
          horizontalScrollBarEnabled: false,
          allowFileAccessFromFileURLs: true,
          allowUniversalAccessFromFileURLs: true,
          mixedContentMode: MixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW,
          // The Jinja2 HTML is self-contained (all CSS inline), but these
          // settings ensure it can load any embedded images or fonts.
          useWideViewPort: true,
          loadWithOverviewMode: true,
          supportZoom: false,
          builtInZoomControls: false,
          displayZoomControls: false,
        ),
        onWebViewCreated: (_) {
          // Controller stored for potential future use (e.g. JS injection).
        },
        onLoadStart: (_, url) {
          debugPrint('InAppWebView loading: $url');
        },
        onLoadStop: (_, url) {
          debugPrint('InAppWebView loaded: $url');
        },
        onReceivedError: (controller, request, error) {
          debugPrint('InAppWebView error [${error.description}]: ${request.url}');
        },
        onProgressChanged: (controller, progress) {
          setState(() {
            _progress = progress / 100.0;
          });
        },
        onConsoleMessage: (controller, message) {
          // Forward any JavaScript console messages for debugging.
          debugPrint('InAppWebView console: [${message.messageLevel}] ${message.message}');
        },
      ),
    );
  }
}
